services:
    db:
        image: postgres:18-alpine
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        build:
            context: ./backend
            target: dev
        working_dir: /app
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
        volumes:
            - ./backend:/app
        ports:
            - "8080:8080"
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
            target: dev
        working_dir: /app
        command: npm run dev -- --hostname 0.0.0.0 --webpack
        env_file:
            - .env
        environment:
            - WATCHPACK_POLLING=true
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        depends_on:
            - backend

volumes:
    pgdata:
